name: Run Twitter Bot

on:
  schedule:
    - cron: '*/10 * * * *' # Runs every 10 minutes
  workflow_dispatch:

jobs:
  run-twitter-bot:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Check internet connection
      run: |
        echo "Checking internet connection..."
        ping -c 4 google.com
        echo "Internet connection check complete."

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Cache dependencies
      uses: actions/cache@v2
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
        restore-keys: |
          ${{ runner.os }}-pip-

    - name: Install dependencies
      run: |
        echo "Creating virtual environment..."
        python -m venv twitterenv
        echo "Virtual environment created."
        echo "Activating virtual environment..."
        . twitterenv/bin/activate
        echo "Virtual environment activated."
        echo "Installing dependencies..."
        pip install -r requirements.txt -v
        echo "Dependencies installed."

    - name: Run Twitter Bot
      env:
        CONSUMER_KEY: ${{ secrets.CONSUMER_KEY }}
        CONSUMER_SECRET: ${{ secrets.CONSUMER_SECRET }}
        ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
        ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}
        CLIENT_ID: ${{ secrets.CLIENT_ID }}
        CLIENT_SECRET: ${{ secrets.CLIENT_SECRET }}
        OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        NVIDIA_API_KEY: ${{ secrets.NVIDIA_API_KEY }}
      run: |
        echo "Activating virtual environment..."
        . twitterenv/bin/activate
        echo "Virtual environment activated."
        echo "Running Twitter Bot..."
        python main.py -v
        echo "Twitter Bot run complete."